# Generated by Django 5.2.6 on 2026-02-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_studentassignmentprogress_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonclassroom',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Monday', 'MONDAY'), ('Tuesday', 'TUESDAY'), ('Wednesday', 'WEDNESDAY'), ('Thursday', 'THURSDAY'), ('Friday', 'FRIDAY'), ('Saturday', 'SATURDAY'), ('Sunday', 'SUNDAY')], default='Monday', max_length=10, null=True),
        ),
    ]
